### PR TITLE
Add support for QNX operating system

### PR DESCRIPTION
**Pull request by flba-eb**
This depends on https://github.com/rust-lang/rust/pull/102701

### CODE REVIEW

**Comment by flba-eb** [comment]
Some tests are failing, could somebody please have a look what the root cause might be?

**Comment by JohnTitor** [comment]
It's a CI issue, let me fix!

**Comment by JohnTitor** [comment]
The issue has been fixed, could you rebase?

**Review by JohnTitor — APPROVED** [review]
Thanks!

**Pull request merged**
