### PR TITLE
Remove the use of `mem::zeroed()` from generated code

### LINKED ISSUE #31: offset_of assumes structure can be zero-initialized
The fix for #23 (in PR #24) calls `mem::zeroed()` to create a zero-initialized version of a structure. However, not all structures can be safely zero-initialized.

I discovered this when attempting to update `libz-sys` to ctest2 0.4.3 to get the fix for #23. One of the structures contained function pointers, which couldn't be zero-initialized, and this resulted in a pile of warnings as well as a runtime panic.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #31

### CODE REVIEW

**Comment by JohnTitor** [comment]
@joshtriplett Do you have any chance to use this patch before merging?

**Comment by joshtriplett** [comment]
@JohnTitor That partially fixes the issue, but the other uses of `zeroed` in the generated code also need updating.

**Comment by JohnTitor** [comment]
Good call, I totally overlooked them.
Now there's no use of `mem::zeroed()`, could you re-check?

**Comment by joshtriplett** [comment]
@JohnTitor That fixed the problem, thank you! I can run the libz-sys systest suite with ctest2 from this branch.

**Pull request merged**
