### PR TITLE
Add support for long double

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Needed for https://github.com/rust-lang/libc/pull/2565.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
ping @JohnTitor

**Comment by JohnTitor** [comment]
Looks fine, could you also add a test case here? https://github.com/JohnTitor/ctest2/tree/master/testcrate/src

**Comment by GuillaumeGomez** [comment]
From what I can read, it's supposed to compare the rust equivalent, however `long double` has no equivalent in Rust. So: how can I add a test for a type which doesn't exist in rust?

**Comment by JohnTitor** [comment]
I wanted to ensure that it works fine by replicating code from the above libc PR, doesn't it make much sense? If not, I'm fine to merge as-is.

**Comment by GuillaumeGomez** [comment]
I can give it a try at least.

**Comment by GuillaumeGomez** [comment]
Let's see how it goes now. :3

**Comment by GuillaumeGomez** [comment]
@JohnTitor Does the test looks ok to you?

**Review by JohnTitor — APPROVED** [review]
Yeah, thanks a lot!

**Comment by GuillaumeGomez** [comment]
Thanks for the release! :)

**Pull request merged**
