### PR TITLE
Add Loongarch64 support

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
Loongarch is a new RISC architecture.
Loongarch doc: https://github.com/loongson-community/LoongArch-Documentation/

### CODE REVIEW

**Comment by JohnTitor** [comment]
I think that isn't an official target of Rust, right? If so, for maintenance reasons, I'd recommend forking and patching yourself.

**Comment by zhaixiaojuan** [comment]
Thank you for your suggestion.
Currently, locally, our team has supported the code of the loongarch64 architecture in rust, libc and etc..., and the build has passed and the relevant tests have been run. The related patches are currently being sorted out. Later plans to submit rust, libc and other codes to the upstream community.

**Comment by JohnTitor** [comment]
Thanks for clarifying, I'd like to hold off this PR until PRs are sent to rustc and libc repos. I'm happy to merge this then :)

**Comment by heiher** [comment]
@JohnTitor The [loongarch64-unknown-linux-gnu](https://github.com/rust-lang/rust/pull/96971) was added as a tier 3 target, could you review this patch again please?

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks for the ping and contribution!

**Pull request merged**
